### ISSUE TITLE
Bug: 缺少 `require`

### ISSUE THREAD

**Issue by KomoriDev** [Agnes4m/nonebot_plugin_l4d2_server#31]
你好，请在这里加上 `require("nonebot_plugin_saa")`
https://github.com/Agnes4m/nonebot_plugin_l4d2_server/blob/0b774490bcf6a309ebfa25839a783cccdc2036d3/nonebot_plugin_l4d2_server/__init__.py#L35-L38

而且应该在 `from .l4d2_data import sq_L4D2` 之前 require

**Comment by Agnes4m** [comment]
已添加saa，抱歉才注意到5555

**Comment by Agnes4m** [comment]
没有问题我就关iss拉
