### ISSUE TITLE
ModuleNotFoundError: No module named 'l4d2_utils'

### ISSUE THREAD

**Issue by PackageInstaller** [Agnes4m/nonebot_plugin_l4d2_server#5]
我用的是基于nonebot的zhenxun_bot

git pull后出现 **ModuleNotFoundError: No module named 'l4d2_utils'** 的依赖报错

已执行过pip install -U nonebot_plugin_l4d2_server，但是还是有这个报错

报错截图以及插件目录结构如下
![image](https://github.com/Agnes4m/nonebot_plugin_l4d2_server/assets/80018096/299a1296-9c08-4d4f-bec8-4c045c1bb12b)

![image](https://github.com/Agnes4m/nonebot_plugin_l4d2_server/assets/80018096/e71bd6b7-bb5c-4114-81a3-ade02ffa9ae5)

**Comment by Agnes4m** [comment]
模块名称问题，已修复

**Comment by PackageInstaller** [comment]
git pull后报错
![image](https://github.com/Agnes4m/nonebot_plugin_l4d2_server/assets/80018096/93d80667-a5f5-488d-8b3a-a2b45dae26e9)

**Comment by Agnes4m** [comment]
很明显你没有重启bot

**Comment by PackageInstaller** [comment]
> 很明显你没有重启bot

重启了

**Comment by Agnes4m** [comment]
很明显，检查报错最后一次的位置，5分钟前修改，如果没有修改说明你git pull失败了

**Comment by PackageInstaller** [comment]
txt_to_img.py对吧，8分钟前

**Comment by Agnes4m** [comment]
已修复
